In [4]:
import numpy as np

In [5]:
lista = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
for linha in lista:
    for celula in linha:
        print(celula, end='; ')
    print()

1; 2; 3; 
4; 5; 6; 


In [7]:
lista

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
lista**10

array([[       1,     1024,    59049],
       [ 1048576,  9765625, 60466176]])

In [9]:
python_puro = [1, 2, 3]

In [12]:
for idx, celula in enumerate(python_puro):
    python_puro[idx] = celula**10

In [13]:
python_puro

[1, 1024, 59049]

In [14]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [15]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [16]:
int('1')

1

In [17]:
int(['1', '2', '3'])

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [23]:

nova_lista = np.array([b'1', b'2', b'3'])

In [24]:
nova_lista.dtype

dtype('S1')

In [25]:
lista_3d = np.array([[[1], [2], [1], [2]]])

In [26]:
lista_3d.shape

(1, 4, 1)

In [28]:
lista_3d.ndim

3

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
lista_aleatoria = np.random.randint(0, 10, 11)
lista_aleatoria

array([6, 0, 0, 2, 8, 7, 3, 4, 8, 0, 7])

In [48]:
lista_aleatoria[0:len(lista_aleatoria)//2] = 20

In [49]:
lista_aleatoria

array([20, 20, 20, 20, 20,  7,  3,  4,  8,  0,  7])

In [40]:
len(lista_aleatoria)

11

In [41]:
len(lista_aleatoria) / 2

5.5

In [42]:
len(lista_aleatoria) // 2

5

In [50]:
lista_3d = np.zeros(shape=(4, 4, 4))

In [51]:
lista_3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
lista_3d[1:3,1:3,1:3] = 5.

In [53]:
lista_3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 5., 5., 0.],
        [0., 5., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 5., 5., 0.],
        [0., 5., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [55]:
lista_3d.shape

(4, 4, 4)

In [56]:
lista_3d[1:3,1:3,1:3].shape

(2, 2, 2)

In [57]:
lista_python = [1, 2, 3]

In [58]:
lista_python2 = lista_python[0:2]

In [59]:
lista_python2[0] = 10

In [60]:
lista_python

[1, 2, 3]

In [61]:
lista_python2

[10, 2]

In [67]:
lista_numpy = np.array([1, 2, 3])

In [68]:
lista_numpy2 = lista_numpy[0:2].copy()

In [69]:
lista_numpy2[0] = 10

In [70]:
lista_numpy

array([1, 2, 3])

In [71]:
lista_numpy2

array([10,  2])

In [115]:
lista_3d = np.array([[
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [119]:
lista_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [128]:
lista_3d.mean(axis=2)

array([[ 2.,  5.,  8.],
       [11., 14., 17.],
       [20., 23., 26.]])

In [171]:
pessoas = np.array(['Monica', 'Adriana', 'Monica', 'Adriana'])

In [178]:
filtro = ((pessoas == 'Adriana') & (pessoas == 'Monica'))

In [179]:
filtro

array([False, False, False, False])

In [180]:
somente_adriana = pessoas[filtro]
somente_adriana

array([], dtype='<U7')

In [161]:
somente_adriana

array(['Adriana', 'Adriana'], dtype='<U7')

In [165]:
type(somente_adriana)

numpy.ndarray

In [162]:
somente_adriana[:] = 'Joyce'

In [167]:
somente_adriana_python_nativo = list(somente_adriana)
somente_adriana_python_nativo

['Joyce', 'Joyce']

In [168]:
type(somente_adriana_python_nativo)

list

In [182]:
!git add cade

5283.17s - pydevd: Sending message related to process being replaced timed-out after 5 seconds
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 17 (delta 6), reused 8 (delta 3), pack-reused 0
Unpacking objects: 100% (17/17), 660.93 KiB | 1.17 MiB/s, done.
From github.com:heliomacedofilho/bootcamp-analise-de-dados-enap-2023
   4a199eb..71a3233  main       -> origin/main
Updating 4a199eb..71a3233
Fast-forward
 .../day 06/exercises/Bruno/exercise_bruno.ipynb    |   422 +
 .../Ricardo/Exercicios_Ricardo_aula6.ipynb         |   244 +
 bootcamp/day 06/exercises/Ricardo/data/README.md   |     0
 .../exercises/Ricardo/data/salarios_RAIS.csv       | 43025 +++++++++++++++++++
 4 files changed, 43691 insertions(+)
 create mode 100644 bootcamp/day 06/exercises/Bruno/exercise_bruno.ipynb
 create mode 100644 bootcamp/day 06/exercises/Ricardo/Exercicios_Ricardo_aula6.ipynb
 create mode 100644 bootcamp/d