# Manipulação de Dados 🪡 🎲 em Alto Desempenho 🚀 🧞‍♂️

## Sumário da Aula

<ul>
    <li>Computação Vetorizada 🧮</li>
    <ul>
        <li>Operandos n-dimensionais (Vetores 🗃️)</li>
        <li>Operações n-dimensionais 🛠️</li>
    </ul>
    <li>Juntando as Peças 🧩</li>
    <ul>
        <li>(Fontes de Dados 🚰 ➕ Manipulação 🪡) <sup>Alto Desempenho 🚀 🧞‍♂️</sup></li>
    </ul>
</ul>

### Biblioteca Principal 📚: numpy

<img src="https://numpy.org/images/logo.svg" width="100" style="float: right;">

In [1]:
!pip install --upgrade numpy --quiet

In [2]:
import numpy as np

## Computação Vetorizada 🧮

<ul>
    <li>Manipulação de Dados 🕵🏽 🎲 em Alto Desempenho 🚀 🧞‍♂️</li>
    <li>NumPy (Numerical Python) é uma das bibliotecas de computação numérica mais importantes do Python.</li>
    <li>Foi projetado para ser eficaz em vetores (muito grandes) de dados. São destaques do NumPy:
        <ul>
            <li><b>ndarray</b>: um array multidimensional eficaz que oferece operações aritméticas rápidas, orientadas a vetores e em alto desempenho, pois
                <ul>
                    <li>internamente, o NumPy armazena dados em um bloco contíguo de memória;</li>
                    <li>seus algoritmos baseados em C evitam a sobrecarga presente com o código Python interpretado; e</li>
                    <li>o NumPy é capaz de operar diretamente em memória, sem qualquer verificação de tipo ou outro
                        <i>overhead</i>.</li>
                </ul>
            </li>
            <li><b>funções matemáticas</b> para operações rápidas em vetores (inteiros) de dados, sem que seja necessário escrever laços;</li>
            <li><b>recursos para álgebra linear</b>, geração de números aleatórios e transformadas de Fourier.</li>
        </ul>
    </li>
</ul>

👉 Referência: <a href='https://numpy.org/doc/stable/'>numpy.org</a>

👉 NumPy <a href='https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf'>cheat sheet</a>

### Operandos n-dimensionais (Vetores 🗃️)

<ul>
    <li>O ndarray do NumPy é um contêiner rápido e flexível para conjuntos (grandes) de dados em Python; em síntese, são:
        <ul>
            <li>multidimensionais;</li>
            <li>os dados são homogêneos; e</li>
            <li>têm um tamanho fixo definido na criação.</li>
        </ul>
    </li>
</ul>

<img src="https://i1.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png"  width="600" style="float: left;">

<pre>Você pode criar um ndarray com a função array e usar uma sequência como parâmetro 

(e.g. lista, lista de listas, etc.)</pre>

In [3]:
data1 = [1, 2, 3]
arr1 = np.array(data1)
arr1

array([1, 2, 3])

In [4]:
data2 = [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [5]:
data3 = [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]
arr3 = np.array(data3)
arr3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

<pre>Você pode realizar operações matemáticas em lote como se fossem operações com escalares</pre>

In [6]:
arr1**10

array([    1,  1024, 59049])

In [7]:
arr1 + arr1

array([2, 4, 6])

<pre>Você pode especificar o tipo dos dados, mas por padrão ele é inferido</pre>

In [8]:
arr1 = np.array(data1)
arr1

array([1, 2, 3])

In [9]:
arr1 = np.array(data1, dtype=np.uint8)
arr1

array([1, 2, 3], dtype=uint8)

<pre>Você pode converter o tipo dos dados</pre>

In [10]:
arr1.astype(np.float64)

array([1., 2., 3.])

In [11]:
arr1.astype(np.string_)

array([b'1', b'2', b'3'], dtype='|S3')

In [12]:
arr1.astype(np.unicode_)

array(['1', '2', '3'], dtype='<U3')

In [13]:
arr1.astype(np.complex64)

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

<pre>Você pode inspecionar os atributos de um vetor n-dimensional</pre>

👉 Tipo do Dado Armazenado

In [14]:
arr1.dtype

dtype('uint8')

In [15]:
arr2.dtype

dtype('int64')

In [16]:
arr3.dtype

dtype('int64')

👉 Formato do Dado Armazenado

In [17]:
arr1.shape

(3,)

In [18]:
arr2.shape

(3, 3)

In [19]:
arr3.shape

(3, 3, 3)

👉 Dimensão do Vetor

In [20]:
arr1.ndim

1

In [21]:
arr2.ndim

2

In [22]:
arr3.ndim

3

#### Quadro-resumo dos métodos de criação de vetores n-dimensionais

<table>
    <tr><th>Método</th><th>Descrição</th></tr>
    <tr><td>array</td><td>Converte os dados de entrada (lista, tupla, array ou outro tipo de sequência) em um ndarray, seja inferindo um dtype ou especificando-o explicitamente; copia os dados de entrada, por padrão</td></tr>
    <tr><td>asarray</td><td>Converte a entrada para um ndarray, mas não copia se a entrada já for um ndarray</td></tr>
    <tr><td>arange</td><td>Como a função embutida range, porém devolve um ndarray em vez de uma lista</td></tr>
    <tr><td>ones, ones_like</td><td>Gera um array somente com 1s, com o formato e o dtype especificados; ones_like aceita outro array e gera um array de 1s com o mesmo formato e o mesmo dtype</td></tr>
    <tr><td>zeros, zeros_like</td><td>Como ones e ones_like, porém gerando arrays com 0s</td></tr>
    <tr><td>empty, empty_like</td><td>Cria novos arrays alocando nova memória, mas não preenche com nenhum valor, como ones e zeros</td></tr>
    <tr><td>full, full_like</td><td>Gera um array com o formato e o dtype especificados, com todos os valores definidos com o "valor de preenchimento" indicado. full_like aceita outro array e gera um array preenchido com o mesmo formato e o mesmo dtype</td></tr>
    <tr><td>eye, identity</td><td>Cria uma matriz-identidade quadrada N x N (1s na diagonal e 0s nas demais posições)</td></tr>
</table>

#### Quadro-resumo dos tipos de dados

<table>
    <tr><th>Tipo de Dado</th><th>Código do Tipo de Dado</th><th>Descrição</th></tr>
    <tr><td>int8, uint8</td><td>i1, u1</td><td>Tipos inteiros de 8 bits (1 byte) com e sem sinal</td></tr>
    <tr><td>int16, uint16</td><td>i2, u2</td><td>Tipos inteiros de 16 bits com e sem sinal</td></tr>
    <tr><td>int32, uint32</td><td>i4, u4</td><td>Tipos inteiros de 32 bits com e sem sinal</td></tr>
    <tr><td>int64, uint64</td><td>i8, u8</td><td>Tipos inteiros de 64 bits com e sem sinal</td></tr>
    <tr><td>float16</td><td>f2</td><td>Ponto flutuante com metade da precisão</td></tr>
    <tr><td>float32</td><td>f4 ou f</td><td>Ponto flutuante padrão com precisão única; compatível com o float de C</td></tr>
    <tr><td>float64</td><td>f8 ou d</td><td>Ponto flutuante padrão com dupla precisão; compatível com o double de C e o objeto float de Python</td></tr>
    <tr><td>float128</td><td>f16 ou g</td><td>Ponto flutuante com precisão estendida</td></tr>
    <tr><td>complex64, complex128, complex256</td><td>c8, c16, c32</td><td>Números complexos representados por dois floats de 32, 64 ou 128, respectivamente</td></tr>
    <tr><td>bool</td><td>?</td><td>Tipo booleano que armazena os valores True e False</td></tr>
    <tr><td>object</td><td>O</td><td>Tipo objeto de Python; um valor pode ser qualquer objeto Python</td></tr>
    <tr><td>string_</td><td>S</td><td>Tipo string ASCII de tamanho fixo (1 byte por caractere); por exemplo, para criar um dtype string com tamanho 1O, utilize 'S10'</td></tr>
    <tr><td>unicode_</td><td>U</td><td>Tipo Unicode de tamanho fixo (número de bytes é específico de cada plataforma); a mesma semântica de especificação de string_ (por exemplo, 'U10')</td></tr>
</table>

### Operações n-dimensionais 🛠️

#### Aritmética Vetorial 👨🏻‍🏫

<pre>O ndarray do NumPy permite vetorização: realizar operações em lotes, sem escrever um laço <i>for</i> </pre>

<pre>Você pode realizar qualquer operação aritmética entre vetores de mesmo tamanho -- a operação será realizada elemento a elemento</pre>

In [23]:
arr1

array([1, 2, 3], dtype=uint8)

In [24]:
arr1 * arr1

array([1, 4, 9], dtype=uint8)

In [25]:
arr1 - arr1

array([0, 0, 0], dtype=uint8)

<pre>Você pode realizar operações aritméticas com escalares -- a operação com o escalar será realizada a cada elemento do vetor</pre>

In [26]:
1 / arr1

array([1.        , 0.5       , 0.33333333])

In [27]:
arr1 ** 2

array([1, 4, 9], dtype=uint8)

<pre>Você pode realizar comparações entre vetores de mesmo tamanho -- a operação resultará em vetores booleanos</pre>

In [28]:
arr1 >= arr1

array([ True,  True,  True])

In [29]:
arr1 > arr1

array([False, False, False])

#### Funções Universais 🪐

<pre>Uma função universal é uma função que executa operações em todos os elementos do vetor n-dimensional.</pre> 

In [30]:
np.sqrt(arr1)

array([1.   , 1.414, 1.732], dtype=float16)

In [31]:
np.exp(arr1)

array([ 2.719,  7.39 , 20.08 ], dtype=float16)

##### Quadro-resumo das funções universais

<table>
    <tr><th>Função</th><th>Descrição</th></tr>
    <tr><td>abs, fabs</td><td>Calcula o valor absoluto de inteiros, números de ponto flutuante e valores complexos para todos os elementos</td></tr>
    <tr><td>sqrt</td><td>Calcula a raiz quadrada de cada elemento (equivalente a arr ** 0.5) </td></tr>
    <tr><td>square</td><td>Calcula o quadrado de cada elemento (equivalente a arr ** 2)</td></tr>
    <tr><td>exp</td><td>Calcula o exponencial ex de cada elemento</td></tr>
    <tr><td>log, log10, log2, log1p</td><td>Logaritmo natural (base e), log na base 10, log na base 2 e log (1 + x), respectivamente</td></tr>
    <tr><td>sign</td><td>Calcula o sinal de cada elemento: 1 (positivo), O (zero) ou -1 (negativo)</td></tr>
    <tr><td>ceil</td><td>Calcula o teto de cada elemento (isto é, o menor inteiro maior ou igual ao número)</td></tr>
    <tr><td>floor</td><td>Calcula o piso de cada elemento (isto é, o maior inteiro menor ou igual ao elemente)</td></tr>
    <tr><td>rint</td><td>Arredonda os elementos para o inteiro mais próximo, preservando o dtype</td></tr>
    <tr><td>modf</td><td>Devolve as partes fracionária e inteira do array como um array separado</td></tr>
    <tr><td>isnan</td><td>Devolve um array booleano indicando se cada valor é NaN (Not a Number)</td></tr>
    <tr><td>isfinite, isinf</td><td>Devolve um array booleano indicando se cada elemento é finito (não inf, não NaN) ou infinito, respectivamente</td></tr>
    <tr><td>cos, cosh, sin, sinh, tan, tanh</td><td>Funções trigonométricas regulares e hiperbólicas</td></tr>
    <tr><td>arccos, arccosh, arcsin, arcsinh, arctan, arctanh</td><td>Funções trigonométricas inversas</td></tr>
    <tr><td>logical_not</td><td>Calcula o valor-verdade de not x para todos os elementos (equivalente a-arr). </td></tr>
    <tr><td>add</td><td>Soma elementos correspondentes em arrays</td></tr>
    <tr><td>subtract</td><td>Subtrai elementos do segundo array do primeiro</td></tr>
    <tr><td>multiply</td><td>Multiplica elementos do array</td></tr>
    <tr><td>divide, floor-divide</td><td>Faz a divisão ou a divisão pelo piso (truncando o resto)</td></tr>
    <tr><td>power</td><td>Eleva os elementos do primeiro array às potências indicadas no segundo array</td></tr>
    <tr><td>maximum, fmax</td><td>Máximo para todos os elementos; fmax ignora NaN</td></tr>
    <tr><td>minimum, fmin</td><td>Mínimo para todos os elementos; fmin ignora NaN</td></tr>
    <tr><td>mod</td><td>Módulo para todos os elementos (resto da divisão)</td></tr>
    <tr><td>copysign</td><td>Copia o sinal dos valores do segundo argumento para os valores do primeiro argumento</td></tr>
    <tr><td>greater, greater_equal, less, less_equal, equal, not_equal</td><td>Faz uma comparação para todos os elementos, produzindo um array booleano (equivalente aos operadores infixos >, >=, <, <=, ==, !=)</td></tr>
    <tr><td>logical_and, logical_or, logical_xor</td><td>Calcula o valor-verdade da operação lógica (equivalente aos operadores infixos &, |, ^) para todos os elementos</td></tr>
</table>

#### Fatiamento Vetorial 🔪

<pre>Você pode fatiar vetores 1-dimensionais -- da mesma forma que em Python nativo ---,</pre>

In [32]:
arr1

array([1, 2, 3], dtype=uint8)

In [33]:
arr1[0]

1

In [34]:
arr1[0:2]

array([1, 2], dtype=uint8)

<pre>e inclusive compor a atribuição de um escalar que será realizada a cada elemento do vetor</pre>

In [35]:
arr1[0:2] = 12

In [36]:
arr1

array([12, 12,  3], dtype=uint8)

<pre>Você pode fatiar vetores 2-bidimensionais -- note que não há <b>todas</b> essas opções em Python nativo</pre>

In [37]:
arr2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [38]:
arr2[0]

array([1, 2, 3])

In [39]:
arr2[0:2]

array([[1, 2, 3],
       [1, 2, 3]])

In [40]:
arr2[0:2,:]

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
arr2[0:2,0:2]

array([[1, 2],
       [1, 2]])

<pre>mais exemplos...</pre>

<img src="https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172114.png" width="300" style="float: left;">

<pre>em python nativo, as fatias são cópias...</pre>

In [42]:
data1

[1, 2, 3]

In [43]:
data1_copy = data1[:]
data1_copy[:] = [3,3,3]
data1_copy

[3, 3, 3]

In [44]:
data1

[1, 2, 3]

<pre>... e em NumPy, as fatias são visualizações.</pre>

In [45]:
arr1

array([12, 12,  3], dtype=uint8)

In [46]:
arr1_copy = arr1[:]
arr1_copy[:] = [3,3,3]
arr1_copy

array([3, 3, 3], dtype=uint8)

In [47]:
arr1

array([3, 3, 3], dtype=uint8)

<pre>No entanto, você pode mudar o comportamento em NumPy utilizando a função copy()</pre>

In [48]:
arr1 = np.array([1,2,3], np.uint8)

In [49]:
arr1_copy = arr1[:].copy()
arr1_copy[:] = [3,3,3]
arr1_copy

array([3, 3, 3], dtype=uint8)

In [50]:
arr1

array([1, 2, 3], dtype=uint8)

#### Métodos Matemáticos e Estatísticos 👩‍🏫

<img src="https://upload.wikimedia.org/wikipedia/pt/c/cd/Nazar%C3%A9_Confusa.jpg" width="300" style="float: right;">

<ul>
    <li>Um conjunto de funções matemáticas é acessível por meio de métodos do vetor n-dimensional e permite
        <ul>
            <li>calcular estatísticas sobre um vetor (inteiro) ou</li>
            <li>calcular estatísticas sobre os dados ao longo de um eixo.</li>
        </ul>
    </li>
    <li>Você pode usar agregações (com frequência chamadas de reduções), como sum, mean e std (desvio-padrão)</li>
</ul>

<img src="https://www.oreilly.com/api/v2/epubs/9781491922927/files/assets/elsp_0105.png" width="300" style="float: left;">

In [51]:
arr3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

<pre>Você pode calcular a média do vetor 3-dimensional</pre>

In [52]:
arr3.mean()

2.0

<pre>Você pode calcular a média ao longo das linhas do vetor 3-dimensional...</pre>

In [53]:
arr3.mean(axis=0)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

<pre>... que equivale ao cálculo a seguir.</pre>

In [54]:
(arr3[0,:,:] + arr3[1,:,:] + arr3[2,:,:])/3

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

<pre>Você pode calcular a média ao longo das colunas do vetor 3-dimensional...</pre>

In [55]:
arr3.mean(axis=1)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

<pre>... que equivale ao cálculo a seguir.</pre>

In [56]:
(arr3[:,0,:] + arr3[:,1,:] + arr3[:,2,:])/3

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

<pre>Você pode calcular a média ao longo das profundidades do vetor 3-dimensional...</pre>

In [57]:
arr3.mean(axis=2)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

<pre>... que equivale ao cálculo a seguir.</pre>

In [58]:
(arr3[:,:,0] + arr3[:,:,1] + arr3[:,:,2])/3

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

##### Quadro-resumo dos métodos estatísticos básicos

<table>
    <tr><th>Método</th><th>Descrição</th></tr>
    <tr><td>sum</td><td>Soma de todos os elementos do array ou ao longo de um eixo; arrays de tamanho zero têm soma igual a O</td></tr>
    <tr><td>mean</td><td>Média aritmética; arrays de tamanho zero têm média NaN</td></tr>
    <tr><td>std, var</td><td>Desvio-padrão e variância, respectivamente, com graus opcionais de ajuste de liberdade (denominador padrão é n)</td></tr>
    <tr><td>min, max</td><td>Mínimo e máximo</td></tr>
    <tr><td>argmin, argmax</td><td>Índices dos elementos mínimo e máximo, respectivamente</td></tr>
    <tr><td>cumsum</td><td>Soma cumulativa dos elementos, começando de O</td></tr>
    <tr><td>cumprod</td><td>Produto cumulativo dos elementos, começando de 1</td></tr>
</table>

#### Indexação Booleana 🗂️

<pre>Lembre-se que você pode realizar operações aritméticas com escalares; igualmente é possível com comparações</pre>

In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [60]:
condition = (names == 'Bob')
condition

array([ True, False, False,  True, False, False, False])

<pre>Você pode passar o vetor de booleanos para filtrar os elementos do vetor...</pre>

In [61]:
names[condition]

array(['Bob', 'Bob'], dtype='<U4')

<pre>e pode inclusive realizar operações no vetor de booleanos utilizados para filtrar os elementos do vetor</pre>

<pre>Não use <b>not</b>, use <b>~</b></pre>

In [62]:
condition = ~condition
condition

array([False,  True,  True, False,  True,  True,  True])

In [63]:
names[condition]

array(['Joe', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')

<pre>Não use <b>or</b>, use <b>|</b></pre>

👉 dica: sempre utilize parênteses para realizar operações lógicas com vetores de booleanos

In [64]:
condition = (names == 'Bob') | (names == 'Will')
condition

array([ True, False,  True,  True,  True, False, False])

In [65]:
names[condition]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

<pre>Não use <b>and</b>, use <b>&</b></pre>

In [66]:
condition = (names == 'Bob') & (names == 'Will')
condition

array([False, False, False, False, False, False, False])

In [67]:
names[condition]

array([], dtype='<U4')

<ul>
    <li>Limitações do NumPy:</li>
        <ul>
            <li>Não há suporte para nomes de colunas;</li>
            <li>NumPy é desenhado para trabalhar com dados homogêneos (apenas um tipo de dados por vetor n-dimensional!); e</li>
            <li>Ausência de métodos úteis de processamento.</li>
        </ul>
    <li>Na próxima aula, veremos uma biblioteca baseada em NumPy para resolver essas limitações: Pandas 🐼</li>
</ul>

## Juntando as Peças 🧩

### (Fontes de Dados 🚰 ➕ Manipulação 🪡) <sup>Alto Desempenho 🚀 🧞‍♂️</sup>

### Funções Auxiliares

In [68]:
import csv, os

def build_path(subfolder = 'raw', filename = ''):
    folderpath = os.path.join(os.getcwd(), os.pardir, 
                              'project', 'data', subfolder)
    folderpath = os.path.abspath(folderpath)
    if not os.path.exists(folderpath): 
        os.makedirs(folderpath)
    return folderpath

In [69]:
def covid_infections_and_deaths(
        filename = 'ALL_HIST_PAINEL_COVID.csv'):
    filepath = os.path.join(build_path(), filename)
    
    covid_infections_and_deaths_data = []
    with open(filepath) as csvfile:
        csvfile_iterator = csv.reader(csvfile)
        header = next(csvfile_iterator)[0].split(';')
        idx_municipio, idx_casos, idx_obitos = \
            header.index('municipio'), \
            header.index('casosNovos'), \
            header.index('obitosNovos')

        for csvfile_row in csvfile_iterator:
            row = csvfile_row[0].split(';')
            if len(header) == len(row) and row[idx_municipio] != '':
                covid_infections_and_deaths_data.append(\
                    [int(row[idx_casos]), int(row[idx_obitos])])

    return covid_infections_and_deaths_data

In [70]:
def case_fatality_rate_pure_python(covid_infections_and_deaths):
    infections = sum(row[0] for row in covid_infections_and_deaths)
    deaths = sum(row[1] for row in covid_infections_and_deaths)
    return deaths/infections

def case_fatality_rate_numpy(covid_infections_and_deaths):
    infections, deaths = covid_infections_and_deaths.sum(axis=0)
    return deaths/infections

<pre>Você pode demonstrar a diferença de desempenho do Python Puro e do NumPy com o caso concreto a seguir</pre>

In [71]:
pure_python_dataset = covid_infections_and_deaths()
numpy_dataset = np.array(pure_python_dataset)

In [72]:
%%time

rate = case_fatality_rate_pure_python(pure_python_dataset)

print('Com Python Puro;')
print('Taxa de Letalidade da Covid no Brasil: ' +
      f'{rate:.2%}.')

Com Python Puro;
Taxa de Letalidade da Covid no Brasil: 1.86%.
CPU times: user 390 ms, sys: 2.48 ms, total: 392 ms
Wall time: 391 ms


In [73]:
%%time

rate = case_fatality_rate_numpy(numpy_dataset)

print('Com NumPy;')
print('Taxa de Letalidade da Covid no Brasil: ' +
      f'{rate:.2%}.')

Com NumPy;
Taxa de Letalidade da Covid no Brasil: 1.86%.
CPU times: user 40.8 ms, sys: 5.6 ms, total: 46.4 ms
Wall time: 45.5 ms


In [74]:
import time

def case_fatality_rate(case_fatality_rate_function, dataset):
    return case_fatality_rate_function(dataset)

def case_fatality_rate_timing(case_fatality_rate_function, dataset):
    start = time.time()
    rate = case_fatality_rate(case_fatality_rate_function, dataset)
    end = time.time()
    return end-start

In [75]:
pure_python_timing = case_fatality_rate_timing(
    case_fatality_rate_pure_python, pure_python_dataset)

numpy_timing = case_fatality_rate_timing(
    case_fatality_rate_numpy, numpy_dataset)

faster = round(pure_python_timing/numpy_timing)

print('Tempo de execução em python puro: ' +
      f'{pure_python_timing:.2} segundos.')
print('Tempo de execução em numpy: ' +
      f'{numpy_timing:.2} segundos.')
print('Observe que a mesma manipulação de dados em NumPy foi ' +
      f'{faster-1} vezes mais rápido do que no python nativo.')

Tempo de execução em python puro: 0.39 segundos.
Tempo de execução em numpy: 0.038 segundos.
Observe que a mesma manipulação de dados em NumPy foi 9 vezes mais rápido do que no python nativo.
