In [1]:
import numpy as np

In [2]:
lista = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
for linha in lista:
    for celula in linha:
        print(celula, end='; ')
    print()

1; 2; 3; 
4; 5; 6; 


In [4]:
lista

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
lista**10

array([[       1,     1024,    59049],
       [ 1048576,  9765625, 60466176]])

In [6]:
python_puro = [1, 2, 3]

In [7]:
for idx, celula in enumerate(python_puro):
    python_puro[idx] = celula**10

In [8]:
python_puro

[1, 1024, 59049]

In [9]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [10]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [11]:
int('1')

1

In [12]:
int(['1', '2', '3'])

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [ ]:

nova_lista = np.array([b'1', b'2', b'3'])

In [ ]:
nova_lista.dtype

In [ ]:
lista_3d = np.array([[[1], [2], [1], [2]]])

In [ ]:
lista_3d.shape

In [ ]:
lista_3d.ndim

In [ ]:
np.identity(3)

In [ ]:
lista_aleatoria = np.random.randint(0, 10, 11)
lista_aleatoria

In [ ]:
lista_aleatoria[0:len(lista_aleatoria)//2] = 20

In [ ]:
lista_aleatoria

In [ ]:
len(lista_aleatoria)

In [ ]:
len(lista_aleatoria) / 2

In [ ]:
len(lista_aleatoria) // 2

In [ ]:
lista_3d = np.zeros(shape=(4, 4, 4))

In [ ]:
lista_3d

In [ ]:
lista_3d[1:3,1:3,1:3] = 5.

In [ ]:
lista_3d

In [ ]:
lista_3d.shape

In [ ]:
lista_3d[1:3,1:3,1:3].shape

In [ ]:
lista_python = [1, 2, 3]

In [ ]:
lista_python2 = lista_python[0:2]

In [ ]:
lista_python2[0] = 10

In [ ]:
lista_python

In [ ]:
lista_python2

In [ ]:
lista_numpy = np.array([1, 2, 3])

In [ ]:
lista_numpy2 = lista_numpy[0:2].copy()

In [ ]:
lista_numpy2[0] = 10

In [ ]:
lista_numpy

In [ ]:
lista_numpy2

In [ ]:
lista_3d = np.array([[
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
lista_3d

In [ ]:
lista_3d.mean(axis=2)

In [ ]:
pessoas = np.array(['Monica', 'Adriana', 'Monica', 'Adriana'])

In [ ]:
filtro = ((pessoas == 'Adriana') & (pessoas == 'Monica'))

In [ ]:
filtro

In [ ]:
somente_adriana = pessoas[filtro]
somente_adriana

In [ ]:
somente_adriana

In [ ]:
type(somente_adriana)

In [ ]:
somente_adriana[:] = 'Joyce'

In [ ]:
somente_adriana_python_nativo = list(somente_adriana)
somente_adriana_python_nativo

In [ ]:
type(somente_adriana_python_nativo)